/**
 * Centralized log messages for the Nucleus game.
 * This file contains all English strings used in the game log,
 * facilitating future internationalization (i18n).
 */

import { TITLES } from './titles';
import { ANNIHILATION_ENERGY_REWARD, DEFEAT_ENERGY_REWARD, FORCE_DECAY_COST } from './economy';

export const LOG_MESSAGES = {
  PHYSICS: {
    ELECTRON_PROTON_REACTION: "⚡ e- + p → n",
    ELECTRON_PASSES_PROTON: "Electron did not react with proton",
    ELECTRON_PASSES_NEUTRON: "Electron did not react with neutron",
    COULOMB_REPULSION_EE: "Coulomb repulsion: e- vs e-",
    PROTON_BLOCKED_BARRIER: "⚠️ Proton was scattered by Coulomb barrier and teleported to another dimension. (+1 Core)",
    PROTON_SCATTERED_BARRIER: "Proton was scattered by Coulomb barrier",
    UNSTABLE_PROTON_CAPTURE: "Unstable proton capture",
    NEUTRON_NOT_ABSORBED_ZERO_BARN: "⚠️ Neutron was not absorbed due to 0 barn and teleported to another dimension. (+1 Core)",
    HIGH_ENERGY_NEUTRON_NOT_ABSORBED_ZERO_BARN: "⚠️ High energy neutron was not absorbed due to 0 barn and teleported to another dimension. (+1 Core)",
    ELECTRON_CAPTURED_VIA_CHANNEL: (mode: string) => `Electron captured via ${mode} channel`,
    ELECTRON_SCATTERING_PREVENTS_CAPTURE: "⚠️ Electron was scattered and teleported to another dimension. (+1 Core)",
    ELECTRON_SCATTERED_STABILITY: "Nuclide did not react with electron due to mass-energy stability",
    ANTI_NUCLIDE_NEUTRALIZED_ALPHA: `💥 Anti-nuclide was defeated: α particle eliminated anti-nuclide! (+${ANNIHILATION_ENERGY_REWARD} MeV)`,
    PROTON_ELECTRON_CONVERSION: (pts: number) => `⚡ p + e- → n (+${pts} PTS)`,
    FISSION_CHAIN_REACTION_TRIGGERED: (count: number) => `⚛️ Fission Chain Reaction: ${count} fissile nuclides were successively reacted!`,
    ANTI_NUCLIDE_PURGED_FISSION: `💥 Anti-nuclide was defeated: Fission eliminated anti-nuclide! (+${ANNIHILATION_ENERGY_REWARD} MeV)`,
    SHOCKWAVE_NEUTRALIZED: (count: number) => `💥 Shockwave defeated ${count} nuclides!`,
    UNCERTAINTY_POSITION: "✨ Uncertainty principle for position!",
    ANNIHILATION_GAMMA: (pts: number) => `💥 Pair Annihilation! Gamma rays may excite other particles (+${pts} PTS)`,
    ANNIHILATION: "💥 Pair Annihilation: Electron and Positron collided and were annihilated!",
  },
  DECAY: {
    ELECTRON_CAPTURE_INTO: (name: string) => `Electron capture into ${name}`,
    TRANSFORMATION_INTO: (name: string) => `Transformation into ${name}`,
    ALPHA_INTO: (name: string) => `α decay into ${name}`,
    BETA_MINUS_INTO: (name: string) => `β- decay into ${name}`,
    BETA_PLUS_INTO: (name: string) => `β+ decay into ${name}`,
    EC_INTO: (name: string) => `Electron capture into ${name}`,
    SF_INTO: (name: string) => `Spontaneous fission into ${name}`,
    NEUTRON_EMISSION_INTO: (name: string) => `n emission into ${name}`,
    TWO_NEUTRON_EMISSION_INTO: (name: string) => `2n emission into ${name}`,
    PROTON_EMISSION_INTO: (name: string) => `p emission into ${name}`,
    TWO_PROTON_EMISSION_INTO: (name: string) => `2p emission into ${name}`,
    IT_INTO: (name: string) => `Isomeric transition`,
    GAMMA_DECAY: "γ decay",
    PURE_ALPHA_INTO: (name: string) => `Pure α decay into ${name}`,
    PURE_BETA_MINUS_INTO: (name: string) => `Pure β- decay into ${name}`,
    BETA_MINUS_N_INTO: (name: string) => `β- decay & n emission into ${name}`,
    BETA_MINUS_ALPHA_INTO: (name: string) => `β- & α decay into ${name}`,
    BETA_MINUS_PROTON_INTO: (name: string) => `β- decay & p emission into ${name}`,
    BETA_MINUS_SF_INTO: (name: string) => `β- decay & SF into ${name}`,
    BETA_PLUS_ALPHA_INTO: (name: string) => `β+ decay & α decay into ${name}`,
    EC_ALPHA_INTO: (name: string) => `EC & α decay into ${name}`,
    DOUBLE_BETA_MINUS_INTO: (name: string) => `2β- decay into ${name}`,
    DOUBLE_BETA_PLUS_INTO: (name: string) => `2β+ decay into ${name}`,
    DOUBLE_ELECTRON_CAPTURE_INTO: (name: string) => `Double electron capture into ${name}`,
    TRIGGER_INTO: (trigger: string, name: string) => `${trigger} into ${name}`,
    FORCED_DECAY: (label: string) => `☢️ Forced Decay: ${label} was selected! (-${FORCE_DECAY_COST} MeV)`,
    DECAY_FAILED_DRIP_LINE: "⚠️ Failed Decay: Target nuclide is outside the drip lines",
    UNKNOWN_INTO: (name: string) => `Unknown decay into ${name}`,
  },
  CAPTURE: {
    PARTICLE_CAPTURED: (type: string, from: string, to: string) => `Captured ${type}: ${from} → ${to}`,
  },
  SKILLS: {
    NOT_ENOUGH_ENERGY: (cost: number) => `⚠️ Not enough energy! Need ${cost} MeV.`,
    STABILIZATION_SUCCESS: `🔬 ${TITLES.STABILIZE}: HP was fully recovered`,
    NUCLEOSYNTHESIS_BOUNDARY: (unlocked: boolean) => `🌟 ${TITLES.NUCLEOSYNTHESIS}: Attempted to synthesize nuclide beyond Og! ${unlocked ? 'Message unlocked' : ''}`,
    OGANESSON_LIMIT: "⚠️ Attempted to synthesize beyond Oganesson!",
    NUCLEOSYNTHESIS_SUCCESS: (name: string) => `🌟 ${TITLES.NUCLEOSYNTHESIS}: Synthesized ${name}!`,
    R_PROCESS_SUCCESS: (count: number) => `🌌 ${TITLES.R_PROCESS}: Absorbed ${count} particles!`,
    MASTERY_CONSUMED: "⚠️ MASTERY CONSUMED: Level reset to 0",
    TIME_FROZEN: "✨ FROZEN TIME",
    TIME_RESTORED: "✨ TIME RESTARTED",
    EXP_REPLICATE_SUCCESS: (name: string) => `🔮 ${TITLES.EXP_REPLICATE}: ${name}!`,
    DEBUG_TRANSFORMED: (name: string) => `🛠️ DEBUG: Transformed into ${name}`,
    DEBUG_SPAWNED: (side: string, name: string) => `🛠️ DEBUG: Spawned ${side} ${name}`,
    DEBUG_CHEAT_ACTIVATED: `🛠️ DEBUG: Cheat Activated (${TITLES.RESEARCH_MISCONDUCT})`,
    SYSTEM_OVERRIDE_SUCCESS: (name: string) => `🌌 ${TITLES.QUANTUM_OVERRIDE}: Reachable configuration established for ${name}!`,
    SKILL_TOGGLE: (name: string, enabled: boolean) => `⚙️ Skill ${name} ${enabled ? 'ENABLED' : 'DISABLED'}`,
    AUTO_STABILIZATION: `⏱ ${TITLES.AUTO_STABILIZATION}: ${TITLES.TEMPORAL_INVERSION} triggered!`,
    TIME_STOP_ACTIVATED: "⏱ TIME STOP: Chronons stabilized",
    TIME_STOP_RELEASED: "⏱ TIME RESTARTED: Chronons released",
    TRANSMUTATION_SUCCESS: (from: string, to: string) => `✨ ${TITLES.TRANSMUTATION}: ${from} → ${to}`,
  },
  HISTORY: {
    ENGRAVED: (name: string) => `📍 ${name} engraved in history!`,
    RHYTHMIC_RESONANCE: `✨ ${TITLES.RHYTHMIC_RESONANCE}: Cost 0 MeV`,
    ORIGIN: "Origin",
    UNKNOWN: "Unknown",
    TRANSMUTATION: TITLES.TRANSMUTATION,
    FUSION: TITLES.FUSION,
    NUCLEAR_FUSION: `Nuclear ${TITLES.FUSION}`,
    FISSION: TITLES.FISSION,
    NUCLEAR_FISSION: `Nuclear ${TITLES.FISSION}`,
    POSITRON_CAPTURE: "Enforced positron capture",
    PROTON_CAPTURE: "Enforced proton capture",
    NEUTRON_CAPTURE: "Neutron capture",
    ELECTRON_CAPTURE_PLAYER: "Enforced electron capture",
    NUCLEOSYNTHESIS: TITLES.NUCLEOSYNTHESIS,
    R_PROCESS: TITLES.R_PROCESS,
    EXP_REPLICATE: TITLES.EXP_REPLICATE,
    MASTERY_LEVEL: "Mastery Level Up",
    QUANTUM_OVERRIDE: TITLES.QUANTUM_OVERRIDE,
    GAMMA_DECAY: "γ decay",
    ALPHA_DECAY: "α decay",
    BETA_MINUS: "β- decay",
    BETA_PLUS: "β+ decay",
    ELECTRON_CAPTURE: "Electron Capture",
    FISSION_SPONTANEOUS: "Spontaneous Fission",
    PROTON_EMISSION: "Proton emission",
    TWO_PROTON_EMISSION: "2p emission",
    NEUTRON_EMISSION: "Neutron emission",
    DEUTERON_EMISSION: "Deuteron emission",
    TRITON_EMISSION: "Triton emission",
    HELIUM3_EMISSION: "Helium-3 emission",
    REACTION_NG: "(n,γ)",
    REACTION_NP: "(n,p)",
    REACTION_N2N: "(n,2n)",
    REACTION_NA: "(n,α)",
    REACTION_ND: "(n,d)",
    REACTION_NT: "(n,t)",
    REACTION_NF: "(n,fission)",
    REACTION_PN: "(p,n)",
    REACTION_P2N: "(p,2n)",
    REACTION_PG: "(p,γ)",
    REACTION_PNP: "(p,n+p)",
    REACTION_PA: "(p,α)",
    REACTION_P2P: "(p,2p)",
    REACTION_PF: "(p,fission)",
    REACTION_PPA: "(p,p+α)",
    REACTION_PD: "(p,d)",
    REACTION_PT: "(p,t)",
    REACTION_PHE3: "(p,He3)",
    DOUBLE_BETA_MINUS: "Double β- decay",
    DOUBLE_BETA_PLUS: "Double β+ decay",
    DOUBLE_ELECTRON_CAPTURE: "Double Electron Capture",
    TWO_NEUTRON_EMISSION: "2n emission",
    ISOMERIC_TRANSITION: "Isomeric Transition",
    B_MINUS_DELAYED_N: (n: number) => `β- delayed ${n}n emission`,
    B_MINUS_DELAYED_ALPHA: "β- & α decay",
    B_MINUS_DELAYED_PROTON: "β- & proton emission",
    B_MINUS_DELAYED_FISSION: "β- & SF",
    B_PLUS_DELAYED_ALPHA: "β+ & α decay",
    B_PLUS_DELAYED_PROTON: "β+ & proton emission",
    B_PLUS_DELAYED_2PROTON: "β+ & 2p emission",
    EC_DELAYED_ALPHA: "EC & alpha decay",
    EC_DELAYED_PROTON: "EC & proton emission",
    EC_DELAYED_2PROTON: "EC & 2p emission",
    EC_DELAYED_FISSION: "EC & SF",
    REINCARNATION: "Reincarnation",
    RESONANCE: "Resonance",
    NOTHINGNESS: "Nothingness",
    TEMPORAL_INVERSION: "Temporal Inversion",
    ANNIHILATION: "Pair Annihilation",
  },
  UNLOCKS: {
    HIDDEN_TITLE_NEUTRON: (bonus: number) => ` 👑 HIDDEN TITLE: Neutron (n-1)! (+${bonus.toLocaleString()} PTS)`,
    NEW_TITLE_Z: (z: number, bonus: number) => ` 🏆 NEW TITLE: Z=${z}! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_UNKNOWN: (bonus: number) => ` ❔ HIDDEN TITLE: Unknown! Encountered an unmeasured decay path. (+${bonus.toLocaleString()} PTS)`,
    GRANDMASTER_SERIES: (group: string, bonus: number) => ` 👑 GRANDMASTER: ${group} Series Completed! (+${bonus.toLocaleString()} PTS)`,
    DOUBLY_MAGIC: (z: number, n: number, bonus: number) => ` 🧙‍♂️✨ DOUBLY MAGIC NUCLEUS! (Z=${z}, N=${n}) (+${bonus.toLocaleString()} PTS)`,
    MAGIC_PROTON_SHELL: (z: number, bonus: number) => ` ✨ MAGIC PROTON SHELL CLOSED (Z=${z})! (+${bonus.toLocaleString()} PTS)`,
    MAGIC_NEUTRON_SHELL: (n: number, bonus: number) => ` ✨ MAGIC NEUTRON SHELL CLOSED (N=${n})! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_EXP_REPLICATE: (bonus: number) => ` ⚛️ HIDDEN TITLE: ${TITLES.EXP_REPLICATE}! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_PAIR_ANNIHILATION: (bonus: number) => ` ☯️ HIDDEN TITLE: ${TITLES.PAIR_ANNIHILATION}! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_PAIR_ANNIHILATION_MASTERED: (bonus: number) => ` ☯️ HIDDEN TITLE: ${TITLES.PAIR_ANNIHILATION}! (Mastered β+ Emission) (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_NEUTRONIZATION: (bonus: number) => ` ⚪ HIDDEN TITLE: ${TITLES.NEUTRONIZATION}! (Mastered p + e- → n reaction) (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_NUCLEOSYNTHESIS: (bonus: number) => ` 🌟 HIDDEN TITLE: ${TITLES.NUCLEOSYNTHESIS}! The Creation of Elements. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_TEMPORAL_INVERSION: (bonus: number) => ` ⏱ HIDDEN TITLE: ${TITLES.TEMPORAL_INVERSION}. (+${bonus.toLocaleString()} PTS 10x Bonus!)`,
    TEMPORAL_INVERSION_BONUS: (bonus: number) => ` ⏱ ${TITLES.TEMPORAL_INVERSION}: 10x Combo Score! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FUSION: (bonus: number) => ` 💥 HIDDEN TITLE: ${TITLES.FUSION}! Two nuclides merged into one (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FISSION: (bonus: number) => ` ☢️ HIDDEN TITLE: ${TITLES.FISSION}! One nuclide split into two (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_ZERO_BARN: (bonus: number) => ` 🌑 HIDDEN TITLE: ${TITLES.ZERO_BARN}! Non-reacting neutrons were teleported to another dimension. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_ELECTRON_SCATTERING: (bonus: number) => ` ↪️ HIDDEN TITLE: ${TITLES.ELECTRON_SCATTERING}! Scattered electrons were teleported to another dimension. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_GLUTTONY: (bonus: number) => ` 🕳️ HIDDEN TITLE: ${TITLES.GLUTTONY}! Committed a deadly sin. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_DEMON_CORE: (bonus: number) => ` 🫀 HIDDEN TITLE: ${TITLES.DEMON_CORE}! Shifted to high difficulty mode. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FORBIDDEN_CAPTURE: (bonus: number) => ` 🌌 HIDDEN TITLE: ${TITLES.FORBIDDEN_CAPTURE}! Captured a positron. (+${bonus.toLocaleString()} PTS)`,
  },
  TUTORIAL: {
    CAPTURE: "Capture particle to transform",
    DECAY: "Decay to become stable",
    DECAY_MANUAL: "Press spacebar or click nuclide to decay",
    DRIP_LINE: "Carefully and Quickly capture particle or decay",
    RECORD_HISTORY: "Click a nuclide figure to record in history",
    SKILL_TOGGLE: "Press 🏆 set skill on/off",
    OGANESSON_CONGRATS: "🌐Congratulations: End of one journey is beginning of another",
    ALL_ELEMENTS_COMPLETE: "🎉 All elements are completed"
  },
  STABILITY: {
    AUTO_STABILIZATION_TEMPORAL: `⏱ ${TITLES.AUTO_STABILIZATION}: ${TITLES.TEMPORAL_INVERSION} triggered!`,
    REINCARNATION_REBORN: (name: string) => `♻️ REINCARNATION: Reborn as ${name}!`,
  },
  EVENTS: {
    ANOMALY_DETECTED: "⚠️ WARNING: ANOMALY DETECTED. ANTI-NUCLIDE MATERIALIZED",
    MATTER_STRUGGLE: (nameF: string, nameE: string, winner: string) => `💥 Matter Struggle: ${nameF} vs ${nameE} -> ${winner} remained`,
    ANNIHILATED_ENEMIES: "Other enemies in the same cell were also annihilated",
    ANNIHILATED_FRIENDS: "Other friends in the same cell were also annihilated",
    CRITICALITY_CHANCE: "⚠️ CRITICALITY ALERT: Fission Chain Chance!",
    BOSS_SPAWN: (z: number, a: number) => `⚠️ Another Nuclide Detected: Z=${z}, A=${a} approaching.`,
    QUANTUM_COHERENCE: "⚠️ QUANTUM COHERENCE: Particle Identity Inversion!",
    STELLAR_WIND: "⚠️ STELLAR WIND: Massive Neutron Flux!",
    COSMIC_RAY_BURST: "⚠️ COSMIC RAY BURST: Massive Proton Flood!",
    VACUUM_FLUCTUATION: "⚠️ VACUUM FLUCTUATION: Massive Electron Storm!",
    POSITRON_MAZE: "⚠️ POSITRON MAZE: Quantum Confinement!",
  },
  SYSTEM: {
    MASTERY_LEVEL_UP: (level: number) => `✨ Mastery LV. ${level}`,
    PERIODIC_TABLE_COMPLETE: "🏆 ACHIEVEMENT: Periodic Table Completed!",
    ANOTHER_NUCLIDE_DEFEATED: `💥 Another nuclide was defeated! (+${DEFEAT_ENERGY_REWARD} MeV)`,
    COLLISION_WITH_NUCLIDE: (camp: string, penalty: number) => `⚠️ Collision with ${camp} Nuclide! HP -${penalty}`,
    DEFEATED_BY_REACTION: (label: string) => `💥 ${label} was defeated by reaction! (+${DEFEAT_ENERGY_REWARD} MeV)`,
    WELCOME_1: "Welcome to the Nucleus!",
    WELCOME_2: "Master radioactive decays to increase your Mastery Level",
    DRIP_LINE_WARNING: "⚠️ Danger: Drip line limit",
    TUTORIAL_COULOMB_BARRIER: "✅Coulomb barrier prevents proton capture",
    TUTORIAL_MASS_STABILITY: "✅Mass stability prevents electron capture",
    TUTORIAL_NEUTRON_CAPTURE: "✅ Uncharged Neutron is Captured",
    STELLAR_FUSION_DEUTERIUM: "Nuclear Fusion: Deuterium Synthesized",
    REACTION_INTO: (label: string, name: string) => `${label} reaction into ${name}`,
    ENFORCED_ELECTRON_CAPTURE_INTO: (name: string) => `Enforced electron capture into ${name}`,
    ENFORCED_POSITRON_CAPTURE_INTO: (name: string) => `Enforced positron capture into ${name}`,
    ENFORCED_PROTON_CAPTURE_INTO: (name: string) => `Enforced proton capture into ${name}`,
    NEUTRON_CAPTURE_INTO: (name: string) => `Neutron capture into ${name}`,
    ENFORCED_CAPTURE_PREFIX: (msg: string) => `⚠️ Enforced Capture! ${msg}`,
    TOTAL_ANNIHILATION: (energy: number) => `🌑 Total Annihilation: Anti-nuclide was converted to ${energy} MeV energy!`,
    TRANSFORMATION_FAILED_DRIP_LINE: "⚠️ Transformation failed: Target nuclide is outside the drip lines",
    SKILL_UNLOCKED_REAL_PHYSICS: `🍎Skill Unlocked: ${TITLES.REAL_PHYSICS}`,
    CAMP_FRIENDLY: "Friendly",
    CAMP_ANOTHER: "Enemy",
    LABEL_ANTI_NUCLIDE: "Anti-nuclide",
    LABEL_ANOTHER_NUCLIDE: "Another nuclide"
  }
};
