/**
 * Centralized log messages for the Nucleus game (Japanese).
 * This file contains all Japanese strings used in the game log.
 */

import { TITLES } from './titles';
import { ANNIHILATION_ENERGY_REWARD, DEFEAT_ENERGY_REWARD, FORCE_DECAY_COST } from './economy';

export const LOG_MESSAGES_JP = {
  PHYSICS: {
    ELECTRON_PROTON_REACTION: "⚡ e- + p → n",
    ELECTRON_PASSES_PROTON: "電子と陽子は無反応",
    ELECTRON_PASSES_NEUTRON: "電子と中性子は無反応",
    COULOMB_REPULSION_EE: "クーロン斥力: e- vs e-",
    PROTON_BLOCKED_BARRIER: "⚠️ クーロン障壁により陽子が散乱され別次元に転送されました (+1 Core)",
    PROTON_SCATTERED_BARRIER: "クーロン障壁により陽子が散乱されました",
    UNSTABLE_PROTON_CAPTURE: "不安定な陽子捕獲",
    NEUTRON_NOT_ABSORBED_ZERO_BARN: "⚠️ 0 barnのため中性子が吸収され別次元に転送されました (+1 Core)",
    HIGH_ENERGY_NEUTRON_NOT_ABSORBED_ZERO_BARN: "⚠️ 0 barnのため高エネルギー中性子が吸収され別次元に転送されました (+1 Core)",
    ELECTRON_CAPTURED_VIA_CHANNEL: (mode: string) => `電子が ${mode} チャネル経由で捕獲されました`,
    ELECTRON_SCATTERING_PREVENTS_CAPTURE: "⚠️ 電子散乱により捕獲されず別次元に転送されました (+1 Core)",
    ELECTRON_SCATTERED_STABILITY: "質量エネルギーの安定性により核種と電子は無反応",
    ANTI_NUCLIDE_NEUTRALIZED_ALPHA: `💥 反核種の撃破: α線により反核種を撃破！ (+${ANNIHILATION_ENERGY_REWARD} MeV)`,
    PROTON_ELECTRON_CONVERSION: (pts: number) => `⚡ p + e- → n (+${pts} PTS)`,
    FISSION_CHAIN_REACTION_TRIGGERED: (count: number) => `⚛️ 核分裂連鎖反応: ${count} 個の核分裂性核種が連鎖的に反応！`,
    ANTI_NUCLIDE_PURGED_FISSION: `💥 反核種の撃破: 核分裂反応により反核種を撃破！ (+${ANNIHILATION_ENERGY_REWARD} MeV)`,
    SHOCKWAVE_NEUTRALIZED: (count: number) => `💥 衝撃波により${count}個の核種を撃破！`,
    UNCERTAINTY_POSITION: "✨ 位置の不確定性原理！",
    ANNIHILATION_GAMMA: (pts: number) => `💥 対消滅！消滅γ線により他粒子を励起 (+${pts} PTS)`,
    ANNIHILATION: "💥 対消滅: 電子と陽電子が衝突して消滅！",
  },
  DECAY: {
    ELECTRON_CAPTURE_INTO: (name: string) => `電子捕獲により${name}に変化`,
    TRANSFORMATION_INTO: (name: string) => `${name}に核変換`,
    ALPHA_INTO: (name: string) => `α崩壊により${name}に変化`,
    BETA_MINUS_INTO: (name: string) => `β-崩壊により${name}に変化`,
    BETA_PLUS_INTO: (name: string) => `β+崩壊により${name}に変化`,
    EC_INTO: (name: string) => `電子捕獲により${name}に変化`,
    SF_INTO: (name: string) => `自発核分裂により${name}に変化`,
    NEUTRON_EMISSION_INTO: (name: string) => `n放出により${name}に変化`,
    TWO_NEUTRON_EMISSION_INTO: (name: string) => `2n放出により${name}に変化`,
    PROTON_EMISSION_INTO: (name: string) => `p放出により${name}に変化`,
    TWO_PROTON_EMISSION_INTO: (name: string) => `2p放出により${name}に変化`,
    IT_INTO: (name: string) => `核異性体転移`,
    GAMMA_DECAY: "γ崩壊",
    PURE_ALPHA_INTO: (name: string) => `純粋なα崩壊により${name}に変化`,
    PURE_BETA_MINUS_INTO: (name: string) => `純粋なβ-崩壊により${name}に変化`,
    BETA_MINUS_N_INTO: (name: string) => `β-n崩壊により${name}に変化`,
    BETA_MINUS_ALPHA_INTO: (name: string) => `β-α崩壊により${name}に変化`,
    BETA_MINUS_PROTON_INTO: (name: string) => `β-p崩壊により${name}に変化`,
    BETA_MINUS_SF_INTO: (name: string) => `β-SFにより${name}に変化`,
    BETA_PLUS_ALPHA_INTO: (name: string) => `β+α崩壊により${name}に変化`,
    EC_ALPHA_INTO: (name: string) => `EC-α崩壊により${name}に変化`,
    DOUBLE_BETA_MINUS_INTO: (name: string) => `二重β-崩壊により${name}に変化`,
    DOUBLE_BETA_PLUS_INTO: (name: string) => `二重β+崩壊により${name}に変化`,
    DOUBLE_ELECTRON_CAPTURE_INTO: (name: string) => `二重電子捕獲により${name}に変化`,
    TRIGGER_INTO: (trigger: string, name: string) => `${trigger} により ${name}に変化`,
    FORCED_DECAY: (label: string) => `☢️ 強制壊変: ${label} が選択されました！ (-${FORCE_DECAY_COST} MeV)`,
    DECAY_FAILED_DRIP_LINE: "⚠️ 壊変失敗: 対象核種が存在限界を超えてしまった",
    UNKNOWN_INTO: (name: string) => `未知の壊変により${name}に変化`,
  },
  CAPTURE: {
    PARTICLE_CAPTURED: (type: string, from: string, to: string) => `${type} を捕獲: ${from} → ${to}`,
  },
  SKILLS: {
    NOT_ENOUGH_ENERGY: (cost: number) => `⚠️ エネルギー不足！ ${cost} MeVが必要です`,
    STABILIZATION_SUCCESS: `🔬 ${TITLES.STABILIZE}: HPを全回復`,
    NUCLEOSYNTHESIS_BOUNDARY: (unlocked: boolean) => `🌟 ${TITLES.NUCLEOSYNTHESIS}: Ogを超える核種の合成を試みました！ ${unlocked ? 'Message unlocked' : ''}`,
    OGANESSON_LIMIT: "⚠️ Ogを超える核種の合成を試みました！",
    NUCLEOSYNTHESIS_SUCCESS: (name: string) => `🌟 ${TITLES.NUCLEOSYNTHESIS}: ${name} を合成しました！`,
    R_PROCESS_SUCCESS: (count: number) => `🌌 ${TITLES.R_PROCESS}: ${count} 個の粒子を捕獲し元素合成しました！`,
    MASTERY_CONSUMED: "⚠️ 退行: 習熟度が0にリセット",
    TIME_FROZEN: "✨ 時よ止まれ",
    TIME_RESTORED: "✨ そして時は動き出す",
    EXP_REPLICATE_SUCCESS: (name: string) => `🔮 ${TITLES.EXP_REPLICATE}: ${name}！`,
    DEBUG_TRANSFORMED: (name: string) => `🛠️ デバッグ: ${name}に核変換`,
    DEBUG_SPAWNED: (side: string, name: string) => `🛠️ デバッグ: ${side} ${name}を生成`,
    DEBUG_CHEAT_ACTIVATED: `🛠️ デバッグ: ${TITLES.RESEARCH_MISCONDUCT}`,
    SYSTEM_OVERRIDE_SUCCESS: (name: string) => `🌌 ${TITLES.QUANTUM_OVERRIDE}: ${name}に核変換可能な構成を確立！`,
    SKILL_TOGGLE: (name: string, enabled: boolean) => `⚙️ スキル ${name} ${enabled ? '有効' : '無効'}`,
    AUTO_STABILIZATION: `⏱ ${TITLES.AUTO_STABILIZATION}: ${TITLES.TEMPORAL_INVERSION}を発動！`,
    TIME_STOP_ACTIVATED: "⏱ 時よ止まれ",
    TIME_STOP_RELEASED: "⏱ そして時は動き出す",
    TRANSMUTATION_SUCCESS: (from: string, to: string) => `✨ ${TITLES.TRANSMUTATION}: ${from} → ${to}`,
  },
  HISTORY: {
    ENGRAVED: (name: string) => `📍 ${name}を歴史に刻んだ！`,
    RHYTHMIC_RESONANCE: "✨ リズミカル共鳴: コスト 0 MeV",
    ORIGIN: "起源",
    UNKNOWN: "未知",
    TRANSMUTATION: TITLES.TRANSMUTATION,
    FUSION: TITLES.FUSION,
    NUCLEAR_FUSION: `Nuclear ${TITLES.FUSION}`,
    FISSION: TITLES.FISSION,
    NUCLEAR_FISSION: `Nuclear ${TITLES.FISSION}`,
    POSITRON_CAPTURE: "強制陽電子捕獲",
    PROTON_CAPTURE: "強制陽子捕獲",
    NEUTRON_CAPTURE: "中性子捕獲",
    ELECTRON_CAPTURE_PLAYER: "強制電子捕獲",
    NUCLEOSYNTHESIS: TITLES.NUCLEOSYNTHESIS,
    R_PROCESS: TITLES.R_PROCESS,
    EXP_REPLICATE: TITLES.EXP_REPLICATE,
    MASTERY_LEVEL: "Mastery Level Up",
    QUANTUM_OVERRIDE: TITLES.QUANTUM_OVERRIDE,
    GAMMA_DECAY: "γ崩壊",
    ALPHA_DECAY: "α崩壊",
    BETA_MINUS: "β-崩壊",
    BETA_PLUS: "β+崩壊",
    ELECTRON_CAPTURE: "電子捕獲",
    FISSION_SPONTANEOUS: "自発核分裂",
    PROTON_EMISSION: "陽子放出",
    TWO_PROTON_EMISSION: "2p放出",
    NEUTRON_EMISSION: "中性子放出",
    DEUTERON_EMISSION: "重水素放出",
    TRITON_EMISSION: "三重水素放出",
    HELIUM3_EMISSION: "He3放出",
    REACTION_NG: "(n,γ)",
    REACTION_NP: "(n,p)",
    REACTION_N2N: "(n,2n)",
    REACTION_NA: "(n,α)",
    REACTION_ND: "(n,d)",
    REACTION_NT: "(n,t)",
    REACTION_NF: "(n,fission)",
    REACTION_PN: "(p,n)",
    REACTION_P2N: "(p,2n)",
    REACTION_PG: "(p,γ)",
    REACTION_PNP: "(p,n+p)",
    REACTION_PA: "(p,α)",
    REACTION_P2P: "(p,2p)",
    REACTION_PF: "(p,fission)",
    REACTION_PPA: "(p,p+α)",
    REACTION_PD: "(p,d)",
    REACTION_PT: "(p,t)",
    REACTION_PHE3: "(p,He3)",
    DOUBLE_BETA_MINUS: "二重β-崩壊",
    DOUBLE_BETA_PLUS: "二重β+崩壊",
    DOUBLE_ELECTRON_CAPTURE: "二重電子捕獲",
    TWO_NEUTRON_EMISSION: "2n放出",
    ISOMERIC_TRANSITION: "核異性体転移",
    B_MINUS_DELAYED_N: (n: number) => `β- ${n}個の遅発中性子放出`,
    B_MINUS_DELAYED_ALPHA: "β- & α崩壊",
    B_MINUS_DELAYED_PROTON: "β- & p放出",
    B_MINUS_DELAYED_FISSION: "β- & SF",
    B_PLUS_DELAYED_ALPHA: "β+ & α崩壊",
    B_PLUS_DELAYED_PROTON: "β+ & p放出",
    B_PLUS_DELAYED_2PROTON: "β+ & 2p放出",
    EC_DELAYED_ALPHA: "EC & α崩壊",
    EC_DELAYED_PROTON: "EC & p放出",
    EC_DELAYED_2PROTON: "EC & 2p放出",
    EC_DELAYED_FISSION: "EC & SF",
    REINCARNATION: "転生",
    RESONANCE: "共鳴",
    NOTHINGNESS: "無",
    TEMPORAL_INVERSION: TITLES.TEMPORAL_INVERSION,
    ANNIHILATION: "対消滅",
  },
  UNLOCKS: {
    HIDDEN_TITLE_NEUTRON: (bonus: number) => ` 👑 隠し実績: 中性子 (n-1)！ (+${bonus.toLocaleString()} PTS)`,
    NEW_TITLE_Z: (z: number, bonus: number) => ` 🏆 実績: Z=${z}！ (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_UNKNOWN: (bonus: number) => ` ❔ 隠し実績: Unknown！ 未知の壊変を発見！ (+${bonus.toLocaleString()} PTS)`,
    GRANDMASTER_SERIES: (group: string, bonus: number) => ` 👑 Grand Master: ${group}系列を全発見！ (+${bonus.toLocaleString()} PTS)`,
    DOUBLY_MAGIC: (z: number, n: number, bonus: number) => ` 🧙‍♂️✨ 二重魔法数！ (Z=${z}, N=${n}) (+${bonus.toLocaleString()} PTS)`,
    MAGIC_PROTON_SHELL: (z: number, bonus: number) => ` ✨ 陽子数が魔法数 (Z=${z})！ (+${bonus.toLocaleString()} PTS)`,
    MAGIC_NEUTRON_SHELL: (n: number, bonus: number) => ` ✨ 中性子数が魔法数 (N=${n})！ (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_EXP_REPLICATE: (bonus: number) => ` ⚛️ 隠し実績: ${TITLES.EXP_REPLICATE}！ (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_PAIR_ANNIHILATION: (bonus: number) => ` ☯️ 隠し実績: ${TITLES.PAIR_ANNIHILATION}！ (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_PAIR_ANNIHILATION_MASTERED: (bonus: number) => ` ☯️ 隠し実績: ${TITLES.PAIR_ANNIHILATION}！ (β+崩壊により習得) (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_NEUTRONIZATION: (bonus: number) => ` ⚪ 隠し実績: ${TITLES.NEUTRONIZATION}！ (p + e- → n 反応を習得) (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_NUCLEOSYNTHESIS: (bonus: number) => ` 🌟 隠し実績: ${TITLES.NUCLEOSYNTHESIS}！ 新たな元素を合成 (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_TEMPORAL_INVERSION: (bonus: number) => ` ⏱ 隠し実績: ${TITLES.TEMPORAL_INVERSION} (+${bonus.toLocaleString()} PTS 10倍ボーナス！)`,
    TEMPORAL_INVERSION_BONUS: (bonus: number) => ` ⏱ ${TITLES.TEMPORAL_INVERSION}: Combo Scoreが10倍！ (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FUSION: (bonus: number) => ` 💥 隠し実績: ${TITLES.FUSION}！ 2つの核種が1つに合体 (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FISSION: (bonus: number) => ` ☢️ 隠し実績: ${TITLES.FISSION}！ 1つの核種が2つに分裂 (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_ZERO_BARN: (bonus: number) => ` 🌑 隠し実績: ${TITLES.ZERO_BARN}！ 核反応を起こさなかった中性子は別次元に転送 (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_ELECTRON_SCATTERING: (bonus: number) => ` ↪️ 隠し実績: ${TITLES.ELECTRON_SCATTERING}！ 電子を散乱して別次元に転送 (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_GLUTTONY: (bonus: number) => ` 🕳️ 隠し実績: ${TITLES.GLUTTONY}！ 大罪を犯しました (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_DEMON_CORE: (bonus: number) => ` 🫀 隠し実績: ${TITLES.DEMON_CORE}！ 高難易度モードに変化 (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FORBIDDEN_CAPTURE: (bonus: number) => ` 🌌 隠し実績: ${TITLES.FORBIDDEN_CAPTURE}！ 陽電子を捕獲 (+${bonus.toLocaleString()} PTS)`,
  },
  TUTORIAL: {
    CAPTURE: "粒子を捕獲して別の核種に変わろう",
    DECAY: "壊変して安定核種になろう",
    DECAY_MANUAL: "スペースキーかDecayを押す ➡ 壊変",
    DRIP_LINE: "慎重かつ迅速に粒子を捕獲/壊変せよ",
    RECORD_HISTORY: "核種のアニメを押して歴史に刻もう",
    SKILL_TOGGLE: "🏆を押してスキルをオン/オフ",
    OGANESSON_CONGRATS: "🌐 おめでとう: １つの旅の終わりは別の旅の始まり",
    ALL_ELEMENTS_COMPLETE: "🎉 周期表の完成"
  },
  STABILITY: {
    AUTO_STABILIZATION_TEMPORAL: `⏱ ${TITLES.AUTO_STABILIZATION}: ${TITLES.TEMPORAL_INVERSION}を発動！`,
    REINCARNATION_REBORN: (name: string) => `♻️ 輪廻転生: ${name}として転生しました！`,
  },
  EVENTS: {
    ANOMALY_DETECTED: "⚠️ 警告: 異常検知、反核種が出現しました",
    MATTER_STRUGGLE: (nameF: string, nameE: string, winner: string) => `💥 核種同士の闘い: ${nameF} vs ${nameE} -> ${winner}が生存`,
    ANNIHILATED_ENEMIES: "同じセル内の他の敵対核種も消滅しました",
    ANNIHILATED_FRIENDS: "同じセル内の他の味方核種も消滅しました",
    CRITICALITY_CHANCE: "⚠️ 臨界警報: 核分裂連鎖が起きる可能性あり",
    BOSS_SPAWN: (z: number, a: number) => `⚠️ 別の核種を検知: Z=${z}, A=${a}が接近中`,
    QUANTUM_COHERENCE: "⚠️ 量子コヒーレンス: 何故か陽子と中性子が反転した！",
    STELLAR_WIND: "⚠️ 星風: 膨大な中性子で満たされた！",
    COSMIC_RAY_BURST: "⚠️ 宇宙線バースト: 膨大な陽子で満たされた！",
    VACUUM_FLUCTUATION: "⚠️ 真空ゆらぎ: 膨大な電子で満たされた！",
    POSITRON_MAZE: "⚠️ 陽電子の迷路: 何故か陽電子に閉じ込められた！",
  },
  SYSTEM: {
    MASTERY_LEVEL_UP: (level: number) => `✨ 習熟度 LV. ${level}`,
    PERIODIC_TABLE_COMPLETE: "🏆 実績: 周期表の完成！",
    ANOTHER_NUCLIDE_DEFEATED: `💥 別の核種を撃破！ (+${DEFEAT_ENERGY_REWARD} MeV)`,
    COLLISION_WITH_NUCLIDE: (camp: string, penalty: number) => `⚠️ ${camp} 核種と衝突！ HP -${penalty}`,
    DEFEATED_BY_REACTION: (label: string) => `💥 反応により${label}を撃破！ (+${DEFEAT_ENERGY_REWARD} MeV)`,
    WELCOME_1: "Nucleusの世界へようこそ！",
    WELCOME_2: "放射性壊変を勉強して習熟度を上げよう",
    DRIP_LINE_WARNING: "⚠️ 危険: 存在限界",
    TUTORIAL_COULOMB_BARRIER: "✅ クーロン障壁により陽子は捕獲不可",
    TUTORIAL_MASS_STABILITY: "✅ 質量安定性により電子は捕獲不可",
    TUTORIAL_NEUTRON_CAPTURE: "✅ 電荷のない中性子は捕獲可",
    STELLAR_FUSION_DEUTERIUM: "核融合: 重水素を合成",
    REACTION_INTO: (label: string, name: string) => `${label}反応により${name}に変化`,
    ENFORCED_ELECTRON_CAPTURE_INTO: (name: string) => `強制電子捕獲により${name}に変化`,
    ENFORCED_POSITRON_CAPTURE_INTO: (name: string) => `強制陽電子捕獲により${name}に変化`,
    ENFORCED_PROTON_CAPTURE_INTO: (name: string) => `強制陽子捕獲により${name}に変化`,
    NEUTRON_CAPTURE_INTO: (name: string) => `中性子捕獲により${name}に変化`,
    ENFORCED_CAPTURE_PREFIX: (msg: string) => `⚠️ 強制捕獲！ ${msg}`,
    TOTAL_ANNIHILATION: (energy: number) => `🌑 完全対消滅: 反核種が${energy} MeV のエネルギーに変換されました！`,
    TRANSFORMATION_FAILED_DRIP_LINE: "⚠️ 核変換失敗: 対象核種が存在限界を超えました",
    SKILL_UNLOCKED_REAL_PHYSICS: `🍎 スキル開放: ${TITLES.REAL_PHYSICS}`,
    CAMP_FRIENDLY: "味方",
    CAMP_ANOTHER: "敵対",
    LABEL_ANTI_NUCLIDE: "反核種",
    LABEL_ANOTHER_NUCLIDE: "別の核種"
  }
};
