/**
 * Centralized log messages for the Nucleus game.
 * This file contains all English strings used in the game log,
 * facilitating future internationalization (i18n).
 */

export const LOG_MESSAGES = {
  PHYSICS: {
    ELECTRON_PROTON_REACTION: "⚡ e- + p → n",
    ELECTRON_PASSES_PROTON: "Electron passes through proton",
    ELECTRON_PASSES_NEUTRON: "Electron passes through neutron",
    COULOMB_REPULSION_EE: "Coulomb repulsion: e- vs e-",
    PROTON_BLOCKED_BARRIER: "⚠️ Proton was blocked by Coulomb barrier. (+1 Core)",
    PROTON_SCATTERED_BARRIER: "Proton was scattered by Coulomb barrier",
    UNSTABLE_PROTON_CAPTURE: "Unstable proton capture",
    ALPHA_BLOCKED_BARRIER: "⚠️ Alpha was blocked by Coulomb barrier.",
    ELECTRON_BLOCKED_BARRIER: "⚠️ Electron was blocked by Coulomb barrier.",
    POSITRON_BLOCKED_BARRIER: "⚠️ Positron was blocked by Coulomb barrier.",
    NEUTRON_NOT_ABSORBED_ZERO_BARN: "⚠️ Neutron was not absorbed due to 0 barn. (+1 Core)",
    HIGH_ENERGY_NEUTRON_NOT_ABSORBED_ZERO_BARN: "⚠️ High energy neutron was not absorbed due to 0 barn. (+1 Core)",
    ELECTRON_CAPTURED_VIA_CHANNEL: (mode: string) => `Electron captured via ${mode} channel`,
    ELECTRON_SCATTERING_PREVENTS_CAPTURE: "⚠️ Electron scattering prevents capture. (+1 Core)",
    ELECTRON_SCATTERED_STABILITY: "Electron scattered due to mass-energy stability",
    ANTI_NUCLIDE_NEUTRALIZED_ALPHA: "✨ ANTI-NUCLIDE NEUTRALIZED: Alpha pulse purged anomaly! (+1000 MeV)",
    PROTON_ELECTRON_CONVERSION: (pts: number) => `⚡ p + e- → n (+${pts} PTS)`,
    FISSION_CHAIN_REACTION_TRIGGERED: (count: number) => `⚛️ FISSION CHAIN REACTION: ${count} nuclides triggered!`,
    ANTI_NUCLIDE_PURGED_FISSION: "💥 ANTI-NUCLIDE PURGED: Fission shockwave dissolved anomaly! (+1000 MeV)",
    UNCERTAINTY_POSITION: "✨ Uncertainty principle for position!",
    DOUBLE_UNCERTAINTY: "✨ Double uncertainty principle!",
    ANNIHILATION_GAMMA: (pts: number) => `💥 ANNIHILATION! Gamma rays may excite other particle (+${pts} PTS)`,
    ANTI_NUCLIDE_NEUTRALIZED: "✨ ANTI-NUCLIDE NEUTRALIZED: Positron absorbed!",
    FISSION_CHAIN_REACTION: (count: number) => `⚛️ FISSION CHAIN REACTION: ${count} nuclei split!`,
    ANNIHILATION: "💥 ANNIHILATION: Electron and Positron collided!",
  },
  DECAY: {
    ELECTRON_CAPTURE_INTO: (name: string) => `Electron capture into ${name}`,
    TRANSFORMATION_INTO: (name: string) => `Transformation into ${name}.`,
    ALPHA_INTO: (name: string) => `α decay into ${name}`,
    BETA_MINUS_INTO: (name: string) => `β- decay into ${name}`,
    BETA_PLUS_INTO: (name: string) => `β+ decay into ${name}`,
    EC_INTO: (name: string) => `EC decay into ${name}`,
    SF_INTO: (name: string) => `Spontaneous fission into ${name}`,
    NEUTRON_EMISSION_INTO: (name: string) => `n emission into ${name}`,
    TWO_NEUTRON_EMISSION_INTO: (name: string) => `2n emission into ${name}`,
    PROTON_EMISSION_INTO: (name: string) => `p emission into ${name}`,
    TWO_PROTON_EMISSION_INTO: (name: string) => `2p emission into ${name}`,
    IT_INTO: (name: string) => `Isomeric transition`,
    GAMMA_DECAY: "γ decay",
    PURE_ALPHA_INTO: (name: string) => `Pure α decay into ${name}`,
    PURE_BETA_MINUS_INTO: (name: string) => `Pure β- decay into ${name}`,
    BETA_MINUS_N_INTO: (name: string) => `β-n decay into ${name}`,
    BETA_MINUS_ALPHA_INTO: (name: string) => `β-α decay into ${name}`,
    BETA_MINUS_PROTON_INTO: (name: string) => `β-p decay into ${name}`,
    BETA_MINUS_SF_INTO: (name: string) => `β-SF into ${name}`,
    BETA_PLUS_ALPHA_INTO: (name: string) => `β+α decay into ${name}`,
    EC_ALPHA_INTO: (name: string) => `ECα decay into ${name}`,
    DOUBLE_BETA_MINUS_INTO: (name: string) => `2β- decay into ${name}`,
    DOUBLE_BETA_PLUS_INTO: (name: string) => `2β+ decay into ${name}`,
    DOUBLE_ELECTRON_CAPTURE_INTO: (name: string) => `Double electron capture into ${name}`,
    TRIGGER_INTO: (trigger: string, name: string) => `${trigger} into ${name}`,
    FORCED_DECAY: (label: string) => `☢️ FORCED DECAY: ${label} selected! (-5 MeV)`,
    DECAY_FAILED_DRIP_LINE: "⚠️ Decay failed: Target nuclide is outside the drip lines.",
    UNKNOWN_INTO: (name: string) => `Unknown decay into ${name}`,
    PAIR_ANNIHILATION: "Pair Annihilation",
    NUCLEAR_FISSION: "Nuclear Fission",
    DOUBLE_BETA_MINUS: "Double Beta Minus Decay",
    DOUBLE_BETA_PLUS: "Double Beta Plus Decay",
    DOUBLE_ELECTRON_CAPTURE: "Double Electron Capture",
    TWO_NEUTRON_EMISSION: "Two Neutron Emission",
    ISOMERIC_TRANSITION: "Isomeric Transition",
    B_MINUS_DELAYED_N: (count: number) => `β- delayed ${count}n emission`,
    B_MINUS_DELAYED_ALPHA: "β- delayed alpha emission",
    B_MINUS_DELAYED_PROTON: "β- delayed proton emission",
    B_MINUS_DELAYED_FISSION: "β- delayed fission",
    B_PLUS_DELAYED_ALPHA: "β+ delayed alpha emission",
    B_PLUS_DELAYED_PROTON: "β+ delayed proton emission",
    B_PLUS_DELAYED_2P: "β+ delayed 2p emission",
    EC_DELAYED_ALPHA: "EC delayed alpha emission",
    EC_DELAYED_PROTON: "EC delayed proton emission",
    EC_DELAYED_2P: "EC delayed 2p emission",
    EC_DELAYED_FISSION: "EC delayed fission"
  },
  CAPTURE: {
    PARTICLE_CAPTURED: (type: string, from: string, to: string) => `Captured ${type}: ${from} → ${to}`,
  },
  SKILLS: {
    NOT_ENOUGH_ENERGY: (cost: number) => `⚠️ Not enough energy! Need ${cost}E.`,
    STABILIZATION_SUCCESS: "🔬 Stabilization: HP Recovered.",
    NUCLEOSYNTHESIS_BOUNDARY: (unlocked: boolean) => `🌟 NUCLEOSYNTHESIS: Boundary reached. ${unlocked ? 'Message unlocked.' : ''}`,
    OGANESSON_LIMIT: "⚠️ Oganesson limit reached!",
    NUCLEOSYNTHESIS_SUCCESS: (name: string) => `🌟 NUCLEOSYNTHESIS: Synthesized ${name}!`,
    R_PROCESS_SUCCESS: (count: number) => `🌌 r-process nucleosynthesis: Absorbed ${count} particles!`,
    MASTERY_CONSUMED: "⚠️ MASTERY CONSUMED: Level reset to 0.",
    TIME_FROZEN: "✨ FROZEN TIME",
    TIME_RESTORED: "✨ TIME RESTORED",
    EXP_REPLICATE_SUCCESS: (name: string) => `🔮 EXP. REPLICATE: ${name}!`,
    DEBUG_TRANSFORMED: (name: string) => `🛠️ DEBUG: Transformed into ${name}`,
    DEBUG_SPAWNED: (side: string, name: string) => `🛠️ DEBUG: Spawned ${side} ${name}`,
    DEBUG_CHEAT_ACTIVATED: "🛠️ DEBUG: Cheat Activated (Research Misconduct)",
    SYSTEM_OVERRIDE_SUCCESS: (name: string) => `🌌 SYSTEM OVERRIDE: Reachable configuration established for ${name}!`,
    SKILL_TOGGLE: (name: string, enabled: boolean) => `⚙️ Skill ${name} ${enabled ? 'ENABLED' : 'DISABLED'}`,
    AUTO_STABILIZATION: "⏱ AUTO-STABILIZATION: Temporal Inversion triggered!",
    TIME_STOP_ALREADY_ACTIVE: "⚠️ TIME STOP: Already active.",
    TIME_STOP_ACTIVATED: "⏱ TIME STOP: Chronons stabilized.",
    TIME_STOP_RELEASED: "⏱ TIME RESUMED: Chronons released.",
    TRANSMUTATION_ALREADY_STABLE: "⚠️ TRANSMUTATION: Already stable.",
    TRANSMUTATION_SUCCESS: (from: string, to: string) => `✨ TRANSMUTATION: ${from} → ${to}`,
    UNKNOWN_DECAY_ALREADY_STABLE: "⚠️ UNKNOWN DECAY: Already stable.",
  },
  HISTORY: {
    ENGRAVED: (name: string) => `📍 ${name} engraved in history!`,
    RHYTHMIC_RESONANCE: "✨ RHYTHMIC RESONANCE: Cost 0E",
    ORIGIN: "Origin",
    UNKNOWN: "Unknown",
    TRANSMUTATION: "Transmutation",
    FUSION: "Fusion",
    NUCLEAR_FUSION: "Nuclear Fusion",
    FISSION: "Fission",
    NUCLEAR_FISSION: "Nuclear Fission",
    POSITRON_CAPTURE: "Enforced positron capture",
    PROTON_CAPTURE: "Enforced proton capture",
    NEUTRON_CAPTURE: "Neutron capture",
    ELECTRON_CAPTURE_PLAYER: "Enforced electron capture",
    NUCLEOSYNTHESIS: "Nucleosynthesis",
    R_PROCESS: "r-process nucleosynthesis",
    EXP_REPLICATE: "Experimental Replication",
    MASTERY_LEVEL: "Mastery Level Up",
    QUANTUM_OVERRIDE: "Quantum Override Transmutation",
    GAMMA_DECAY: "γ decay",
    ALPHA_DECAY: "α decay",
    BETA_MINUS: "β- decay",
    BETA_PLUS: "β+ decay",
    ELECTRON_CAPTURE: "Electron capture",
    FISSION_SPONTANEOUS: "Spontaneous fission",
    PROTON_EMISSION: "Proton emission",
    TWO_PROTON_EMISSION: "2p Decay",
    NEUTRON_EMISSION: "Neutron emission",
    DEUTERON_EMISSION: "Deuteron emission",
    TRITON_EMISSION: "Triton emission",
    HELIUM3_EMISSION: "Helium-3 emission",
    REACTION_NG: "(n,γ)",
    REACTION_NP: "(n,p)",
    REACTION_N2N: "(n,2n)",
    REACTION_NA: "(n,α)",
    REACTION_ND: "(n,d)",
    REACTION_NT: "(n,t)",
    REACTION_NF: "(n,fission)",
    REACTION_PN: "(p,n)",
    REACTION_P2N: "(p,2n)",
    REACTION_PG: "(p,γ)",
    REACTION_PNP: "(p,n+p)",
    REACTION_PA: "(p,α)",
    REACTION_P2P: "(p,2p)",
    REACTION_PF: "(p,fission)",
    REACTION_PPA: "(p,p+α)",
    REACTION_PD: "(p,d)",
    REACTION_PT: "(p,t)",
    REACTION_PHE3: "(p,He3)",
    DOUBLE_BETA_MINUS: "Double Beta Minus Decay",
    DOUBLE_BETA_PLUS: "Double Beta Plus Decay",
    DOUBLE_ELECTRON_CAPTURE: "Double Electron Capture",
    TWO_NEUTRON_EMISSION: "Two Neutron Emission",
    ISOMERIC_TRANSITION: "Isomeric Transition",
    B_MINUS_DELAYED_N: (n: number) => `β- delayed ${n}n emission`,
    B_MINUS_DELAYED_ALPHA: "β- delayed alpha emission",
    B_MINUS_DELAYED_PROTON: "β- delayed proton emission",
    B_MINUS_DELAYED_FISSION: "β- delayed fission",
    B_PLUS_DELAYED_ALPHA: "β+ delayed alpha emission",
    B_PLUS_DELAYED_PROTON: "β+ delayed proton emission",
    B_PLUS_DELAYED_2PROTON: "β+ delayed 2p emission",
    EC_DELAYED_ALPHA: "EC delayed alpha emission",
    EC_DELAYED_PROTON: "EC delayed proton emission",
    EC_DELAYED_2PROTON: "EC delayed 2p emission",
    EC_DELAYED_FISSION: "EC delayed fission",
    REINCARNATION: "Reincarnation",
    RESONANCE: "Resonance",
    NOTHINGNESS: "Nothingness",
    TEMPORAL_INVERSION: "Temporal Inversion",
    ANNIHILATION: "Annihilation",
  },
  UNLOCKS: {
    HIDDEN_TITLE_NEUTRON: (bonus: number) => ` 👑 HIDDEN TITLE: Neutron (n)! (+${bonus.toLocaleString()} PTS)`,
    NEW_TITLE_Z: (z: number, bonus: number) => ` 🏆 NEW TITLE: Z=${z}! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_UNKNOWN: (bonus: number) => ` ❔ HIDDEN TITLE: Unknown! Encountered an unmeasured decay path. (+${bonus.toLocaleString()} PTS)`,
    GRANDMASTER_SERIES: (group: string, bonus: number) => ` 👑 GRANDMASTER: ${group} Series Completed! (+${bonus.toLocaleString()} PTS)`,
    DOUBLY_MAGIC: (z: number, n: number, bonus: number) => ` 🧙‍♂️✨ DOUBLY MAGIC NUCLEUS! (Z=${z}, N=${n}) (+${bonus.toLocaleString()} PTS)`,
    MAGIC_PROTON_SHELL: (z: number, bonus: number) => ` ✨ MAGIC PROTON SHELL CLOSED (Z=${z})! (+${bonus.toLocaleString()} PTS)`,
    MAGIC_NEUTRON_SHELL: (n: number, bonus: number) => ` ✨ MAGIC NEUTRON SHELL CLOSED (N=${n})! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_EXP_REPLICATE: (bonus: number) => ` ⚛️ HIDDEN TITLE: Exp. Replicate! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_PAIR_ANNIHILATION: (bonus: number) => ` ☯️ HIDDEN TITLE: Pair annihilation! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_PAIR_ANNIHILATION_MASTERED: (bonus: number) => ` ☯️ HIDDEN TITLE: Pair annihilation! (Mastered β+ Emission) (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_NEUTRONIZATION: (bonus: number) => ` ⚪ HIDDEN TITLE: Neutronization! (Mastered p + e- → n reaction) (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_NUCLEOSYNTHESIS: (bonus: number) => ` 🌟 HIDDEN TITLE: Nucleosynthesis! The Creation of Elements. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_TEMPORAL_INVERSION: (bonus: number) => ` ⏱ HIDDEN TITLE: Temporal Inversion. (+${bonus.toLocaleString()} PTS 10x Bonus!)`,
    TEMPORAL_INVERSION_BONUS: (bonus: number) => ` ⏱ TEMPORAL INVERSION: 10x Combo Score! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FUSION: (bonus: number) => ` 💥 HIDDEN TITLE: Fusion! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FISSION: (bonus: number) => ` ☢️ HIDDEN TITLE: Fission! Breaking the Nucleus. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_ZERO_BARN: (bonus: number) => ` 🌑 HIDDEN TITLE: zero barn! Neutrons flow through you. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_ELECTRON_SCATTERING: (bonus: number) => ` ↪️ HIDDEN TITLE: Electron scattering! Repelling electrons at low stability! (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_GLUTTONY: (bonus: number) => ` 🕳️ HIDDEN TITLE: Gluttony! The grid has been consumed. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_DEMON_CORE: (bonus: number) => ` 🫀 HIDDEN TITLE: Demon core! Attempting the impossible from the brink. (+${bonus.toLocaleString()} PTS)`,
    HIDDEN_TITLE_FORBIDDEN_CAPTURE: (bonus: number) => ` 🌌 HIDDEN TITLE: Forbidden Capture! Consumed the elusive anti-matter. (+${bonus.toLocaleString()} PTS)`,
    NEW_TITLE_GROUP: (group: string) => `🏆 NEW TITLE: ${group}!`,
  },
  TUTORIAL: {
    CAPTURE: "Capture particle to transform",
    DECAY: "Decay to become stable",
    DECAY_MANUAL: "Press spacebar or click nuclide to decay",
    DRIP_LINE: "Carefully and Quickly capture particle or decay",
    RECORD_HISTORY: "Click a nuclide figure to record in history",
    SKILL_TOGGLE: "Press 🏆 set skill on/off",
    OGANESSON_CONGRATS: "🌐Congratulations: End of one journey is beginning of another",
    ALL_ELEMENTS_COMPLETE: "🎉 All elements are completed"
  },
  STABILITY: {
    REINCARNATION: "♻️ REINCARNATION: Nucleus reborn from the pool.",
    AUTO_STABILIZATION_TEMPORAL: "⏱ AUTO-STABILIZATION: Temporal Inversion triggered!",
    REINCARNATION_REBORN: (name: string) => `♻️ REINCARNATION: Reborn as ${name}!`,
  },
  EVENTS: {
    ANOMALY_DETECTED: "⚠️ WARNING: ANOMALY DETECTED. ANTI-NUCLIDE MATERIALIZED.",
    MATTER_STRUGGLE: (nameF: string, nameE: string, winner: string) => `💥 Matter Struggle: ${nameF} vs ${nameE} -> ${winner} remained`,
    ANNIHILATED_ENEMIES: "   (Other enemies in the cell were also annihilated)",
    ANNIHILATED_FRIENDS: "   (Other friends in the cell were also annihilated)",
    CRITICALITY_ALERT: "⚠️ CRITICALITY ALERT: Fission Chain Reaction imminent!",
    CRITICALITY_CHANCE: "⚠️ CRITICALITY ALERT: Fission Chain Chance!",
    BOSS_SPAWN: (z: number, a: number) => `⚠️ ANOTHER NUCLIDE DETECTED: Z=${z}, A=${a} approaching.`,
    QUANTUM_COHERENCE: "⚠️ QUANTUM COHERENCE: Particle Identity Inversion!",
    STELLAR_WIND: "⚠️ STELLAR WIND: Massive Neutron Flux!",
    COSMIC_RAY_BURST: "⚠️ COSMIC RAY BURST: Massive Proton Flood!",
    VACUUM_FLUCTUATION: "⚠️ VACUUM FLUCTUATION: Massive Electron Storm!",
    POSITRON_MAZE: "⚠️ POSITRON MAZE: Quantum Confinement!",
    BACKGROUND_RADIATION: "🌌 Background radiation fluctuates...",
  },
  SYSTEM: {
    MASTERY_LEVEL_UP: (level: number) => `✨ Mastery LV. ${level}`,
    MASTERY_LEVEL_LABEL: (level: number) => `Mastery Level ${level}`,
    PERIODIC_TABLE_COMPLETE: "🏆 ACHIEVEMENT: Periodic Table Completed!",
    ANOTHER_NUCLIDE_DEFEATED: "💥 ANOTHER NUCLIDE DEFEATED! (+1E)",
    COLLISION_WITH_NUCLIDE: (camp: string, penalty: number) => `⚠️ COLLISION WITH ${camp} NUCLIDE! HP -${penalty}`,
    DEFEATED_BY_REACTION: (label: string) => `💥 ${label} DEFEATED BY REACTION! (+1E)`,
    WELCOME_1: "Welcome to the Nucleus!",
    WELCOME_2: "Master radioactive decays to increase your Mastery Level.",
    DRIP_LINE_WARNING: "⚠️ Danger: Drip line limit",
    TUTORIAL_COULOMB_BARRIER: "✅Coulomb barrier prevents proton capture",
    TUTORIAL_MASS_STABILITY: "✅Mass stability prevents electron capture",
    TUTORIAL_NEUTRON_CAPTURE: "✅ UNCHARGED NEUTRON IS CAPTURED",
    STELLAR_FUSION_DEUTERIUM: "Nuclear Fusion: Deuterium Synthesized.",
    REACTION_INTO: (label: string, name: string) => `${label} reaction into ${name}`,
    ENFORCED_ELECTRON_CAPTURE_INTO: (name: string) => `Enforced electron capture into ${name}`,
    ENFORCED_POSITRON_CAPTURE_INTO: (name: string) => `Enforced positron capture into ${name}`,
    ENFORCED_PROTON_CAPTURE_INTO: (name: string) => `Enforced proton capture into ${name}`,
    NEUTRON_CAPTURE_INTO: (name: string) => `Neutron capture into ${name}`,
    ENFORCED_CAPTURE_PREFIX: (msg: string) => `⚠️ ENFORCED CAPTURE! ${msg}`,
    TOTAL_ANNIHILATION: (energy: number) => `🌑 TOTAL ANNIHILATION: Core matter converted to ${energy} MeV energy!`,
    TRANSFORMATION_FAILED_DRIP_LINE: "⚠️ Transformation failed: Target nuclide is outside the drip lines.",
    SKILL_UNLOCKED_REAL_PHYSICS: "🍎Skill Unlocked: Real Physics",
    NUCLEAR_FUSION: "Nuclear Fusion",
    CAMP_FRIENDLY: "FRIENDLY",
    CAMP_ANOTHER: "ANOTHER",
    LABEL_ANTI_NUCLIDE: "ANTI-NUCLIDE",
    LABEL_ANOTHER_NUCLIDE: "ANOTHER NUCLIDE"
  }
};
