import { GameState, DecayMode } from '../types';
import { GRID_WIDTH, GRID_HEIGHT, INITIAL_HP, INITIAL_NUCLIDE, HISTORY_METHODS, LOG_MESSAGES } from '../constants';
import { TITLES } from '../constants/titles';

/**
 * Provides the clean slate initial state for the Nucleus game engine.
 * Isolated for clean state management and consistent resetting.
 */
export const getInitialState = (): GameState => ({
    turn: 0,
    score: 0,
    energyPoints: 0,
    playerPos: { x: Math.floor(GRID_WIDTH / 2), y: Math.floor(GRID_HEIGHT / 2) },
    gridEntities: [],
    currentNuclide: INITIAL_NUCLIDE,
    tranquiloTurnCount: 0,
    // Add missing evolutionHistory property to fix GameState type compatibility error
    evolutionHistory: {},
    hp: INITIAL_HP,
    maxHp: INITIAL_HP,
    messages: [LOG_MESSAGES.SYSTEM.WELCOME_1, LOG_MESSAGES.SYSTEM.WELCOME_2],
    gameOver: false,
    gameOverReason: undefined,
    loadingData: false,
    unlockedElements: [], 
    unlockedGroups: [],
    disabledSkills: [],
    effects: [],
    combo: 0,
    maxCombo: 0,
    lastComboTime: 0,
    isTimeStopped: false,
    playerLevel: 0,
    masteredDecays: [],
    comboScore: 0,
    consecutiveProtons: 0,
    consecutiveNeutrons: 0,
    consecutiveElectrons: 0,
    lastConsumedType: null,
    reincarnations: 0,
    magicBarrierCharges: 0,
    elapsedTime: 0,
    recordTime: undefined,
    achievementTimes: {},
    tutorialMessage: LOG_MESSAGES.TUTORIAL.CAPTURE,
    tutorialStartTurn: 0,
    hasSeenDecayTutorial: false,
    hasSeenCaptureTutorial: false,
    hasSeenDripLineTutorial: false,
    hasSeenEngraveTutorial: false,
    hasSeenSkillToggleTutorial: false,
    comboOrigin: undefined,
    reincarnationPool: { p: 0, n: 0, e: 0 },
    hasPerformedActiveReincarnation: false,
    emptyTurnCount: 0,
    persistentPath: undefined,
    pathExpiryTurn: 0,
    realPhysicsUnlockProgress: {
        hasScatteredProton: false,
        hasScatteredElectron: false,
        hasAbsorbedNeutron: false,
    },
    decayStats: {
        [DecayMode.ALPHA]: 0,
        [DecayMode.BETA_MINUS]: 0,
        [DecayMode.BETA_PLUS]: 0,
        [DecayMode.ELECTRON_CAPTURE]: 0,
        [DecayMode.SPONTANEOUS_FISSION]: 0,
        [DecayMode.NEUTRON_EMISSION]: 0,
        [DecayMode.PROTON_EMISSION]: 0,
        [DecayMode.GAMMA]: 0,
        'PURE_ALPHA': 0,
        'PURE_BETA_MINUS': 0,
        [DecayMode.DOUBLE_BETA_MINUS]: 0,
        [DecayMode.B_MINUS_N]: 0,
        [DecayMode.B_MINUS_ALPHA]: 0,
        [DecayMode.B_MINUS_PROTON]: 0,
        [DecayMode.B_MINUS_SF]: 0,
        [DecayMode.B_PLUS_ALPHA]: 0,
        [DecayMode.EC_ALPHA]: 0,
    },
    reactionStats: {
        [HISTORY_METHODS.REACTION_NG]: 0,
        [HISTORY_METHODS.REACTION_NP]: 0,
        [HISTORY_METHODS.REACTION_N2N]: 0,
        [HISTORY_METHODS.REACTION_NA]: 0,
        [HISTORY_METHODS.REACTION_NF]: 0,
        [HISTORY_METHODS.REACTION_PA]: 0,
    }
});